# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 89)
        self.makeScheduleBtn = QtWidgets.QPushButton(Form)
        self.makeScheduleBtn.setGeometry(QtCore.QRect(40, 50, 499, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.makeScheduleBtn.setFont(font)
        self.makeScheduleBtn.setObjectName("makeScheduleBtn")
        self.editBtn = QtWidgets.QPushButton(Form)
        self.editBtn.setGeometry(QtCore.QRect(40, 20, 499, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактор расписания"))
        self.makeScheduleBtn.setText(_translate("Form", "Составить расписание"))
        self.editBtn.setText(_translate("Form", "Редактировать базы данных"))
