# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 333)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 501, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teachersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teachersBtn.setFont(font)
        self.teachersBtn.setObjectName("teachersBtn")
        self.horizontalLayout.addWidget(self.teachersBtn)
        self.classroomsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.classroomsBtn.setFont(font)
        self.classroomsBtn.setObjectName("classroomsBtn")
        self.horizontalLayout.addWidget(self.classroomsBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupsBtn.setFont(font)
        self.groupsBtn.setObjectName("groupsBtn")
        self.horizontalLayout_2.addWidget(self.groupsBtn)
        self.lessonsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lessonsBtn.setFont(font)
        self.lessonsBtn.setObjectName("lessonsBtn")
        self.horizontalLayout_2.addWidget(self.lessonsBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.makeScheduleBtn = QtWidgets.QPushButton(Form)
        self.makeScheduleBtn.setGeometry(QtCore.QRect(40, 210, 499, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.makeScheduleBtn.setFont(font)
        self.makeScheduleBtn.setObjectName("makeScheduleBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактор расписания"))
        self.label.setText(_translate("Form", "Базы данных"))
        self.teachersBtn.setText(_translate("Form", "Учителя"))
        self.classroomsBtn.setText(_translate("Form", "Кабинеты"))
        self.groupsBtn.setText(_translate("Form", "Классы"))
        self.lessonsBtn.setText(_translate("Form", "Уроки"))
        self.makeScheduleBtn.setText(_translate("Form", "Составить расписание"))
