# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 90, 700, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.scheduleSpace = QtWidgets.QWidget(Form)
        self.scheduleSpace.setGeometry(QtCore.QRect(10, 100, 700, 460))
        self.scheduleSpace.setObjectName("scheduleSpace")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 326, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.currentScheduleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.currentScheduleLabel.setObjectName("currentScheduleLabel")
        self.horizontalLayout_6.addWidget(self.currentScheduleLabel)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.selectScheduleBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.selectScheduleBtn.setObjectName("selectScheduleBtn")
        self.horizontalLayout_5.addWidget(self.selectScheduleBtn)
        self.exportBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout_5.addWidget(self.exportBtn)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 219, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.groupSelect = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupSelect.sizePolicy().hasHeightForWidth())
        self.groupSelect.setSizePolicy(sizePolicy)
        self.groupSelect.setObjectName("groupSelect")
        self.horizontalLayout.addWidget(self.groupSelect)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Составить расписание"))
        self.label_3.setText(_translate("Form", "Текущий шаблон:"))
        self.currentScheduleLabel.setText(_translate("Form", "---"))
        self.selectScheduleBtn.setText(_translate("Form", "Выбрать шаблон"))
        self.exportBtn.setText(_translate("Form", "Экспорт"))
        self.label.setText(_translate("Form", "Класс:"))
